### ISSUE TITLE
Type-based filters are being called on every admin page instead of only on that type's page

### ISSUE THREAD

**Issue by naomicbush** [codepress/codepress-admin-columns#52]
For example, I'm using `cac/columns/custom/type=user`. This filter should only be called on the admin pages for Users. Instead, it's being called on *every* admin page.

**Comment by tobiasschutter** [comment]
We have a free starter-kit available for creating a column for Admin Columns: https://www.admincolumns.com/documentation/developer-docs/creating-new-column-type/

Filter documenation: https://www.admincolumns.com/documentation/developer-docs/filter-reference/cac-columns-custom/
