### ISSUE TITLE
filters for custom pods types show database id instead of title field

### ISSUE THREAD

**Issue by MaartenvanLoon** [codepress/codepress-admin-columns#54]
Hello,

I bought this plugin for its sorting and filter options for pods custom post types. I have problems with the filters.

This custom post type has some advanced pods content types. (like customer for example). In pods you can choose a field to use as the title field (the field you want to have visible to identify the customer). However, the filter option does not use this title field, but the unique database id instead, which make filtering impossible. I need to see the column values in the filter (customer names in this case).

I've added 2 screenshots:
1: see column "Klant" (human readable client names)
2: see filter "Klant" (shows client unique db id's)

**Comment by tobiasschutter** [comment]
Hi Maarten, I am going through old tickets and bumped into yours. Do you know if your issue has been resolved yet in the latest release?

I have tried to reproduce, but I couldn't find a "User type" pods field. 

It also possible to modify the labels with our filter ```cac/addon/filtering/options```. This will enable you to display the clients name with a bit of PHP. Have a look at our documentation for more details: https://www.admincolumns.com/documentation/developer-docs/filter-reference/cac-addon-filtering-options/

If you still need any help let me know.

- Tobias
