### ISSUE TITLE
Set column width in px instead of %

### ISSUE THREAD

**Issue by davidmosterd** [codepress/codepress-admin-columns#67]
The slider to adjust the column width is done with a slider and uses %. Pixels is another unit that might be beneficial if a certain value requires a certain amount of pixels.

comes from: https://www.admincolumns.com/forums/topic/column-width/

**Comment by tobiasschutter** [comment]
I have moved the ticket, so this one will be closed. 
I have made a proposal, it can be discussed here: https://github.com/codepress/admin-columns-issues/issues/139
